### PR TITLE
Add optional ExecStartPost command

### PR DESCRIPTION
**Pull request by aderixon**
* Add optional ExecStartPost command

Allow optional command to be run after container start. (E.g. to send a notification.)

* Document container_start_post in README

### CODE REVIEW

**Review by mhutter — CHANGES_REQUESTED** [review]
Commit message references #1, is that deliberatly?

**Comment by aderixon** [comment]
Sorry, not sure where that crept in. Not related to the linked request.

**Comment by mhutter** [comment]
Sorry, totally forgot about this one 🤦‍♂

**Comment by aderixon** [comment]
So did I but thanks!

**Pull request merged**
